### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by Swati4star** [CapsLockHacks/HackNSIT#1]
The app is comstantly crashing. 
Logcat : 

>  FATAL EXCEPTION: main
>                                                                            Process: com.example.mayank.hacknsit, PID: 4394
>                                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
>                                                                                at com.example.mayank.hacknsit.fragments.DashboardFragment$4.done(DashboardFragment.java:278)
>                                                                                at com.example.mayank.hacknsit.fragments.DashboardFragment$4.done(DashboardFragment.java:274)
>                                                                                at com.parse.ParseTaskUtils$2$1.run(ParseTaskUtils.java:115)
>                                                                                at android.os.Handler.handleCallback(Handler.java:739)
>                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                                at android.os.Looper.loop(Looper.java:148)
>                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
>                                                                                at java.lang.reflect.Method.invoke(Native Method)
>                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by bohrium272** [comment]
Please try it out now. Hopefully it's fixed.

**Comment by Swati4star** [comment]
That one is fixed.
But getting another one now.
After entering input calories as 100 and clicking 'Find Recipes', the app crashed.

> Process: com.example.mayank.hacknsit, PID: 3572
>                                                                            java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
>                                                                                at android.widget.ArrayAdapter.getCount(ArrayAdapter.java:337)
>                                                                                at android.widget.ListView.setAdapter(ListView.java:491)
>                                                                                at com.example.mayank.hacknsit.fragments.RecipesFragment$1$1$1.run(RecipesFragment.java:110)
>                                                                                at android.os.Handler.handleCallback(Handler.java:739)
>                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                                at android.os.Looper.loop(Looper.java:148)
>                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
>                                                                                at java.lang.reflect.Method.invoke(Native Method)
>                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
